name: build PRs

on:
  pull_request:
    types: [ opened, reopened, synchronize ]

jobs:
  clang-format:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 1
      - name: clang-format
        run: |
          git submodule update --init --recursive
          docker run --rm -v ${PWD}:/src xianpengshen/clang-tools:22 clang-format --dry-run --Werror $(find src include -type f \( -name "*.c" -o -name "*.cpp" -o -name "*.h" -o -name "*.hpp" \))
  build-binary:
    name: build-binary
    runs-on: ubuntu-24.04
    needs: clang-format
    steps:
      - name: checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 1
      - name: Docker caching
        uses: AndreKurait/docker-cache@0.7.0
        id: cache
        continue-on-error: true
        with:
          key: nusspli-docker-cache-${{ hashFiles('Dockerfile') }}
      - name: Build docker image
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          docker build . -t builder
      - name: build artifacts
        run: |
          docker run --rm -v ${PWD}:/project builder python3 build.py
      - name: Upload Aroma version
        uses: actions/upload-artifact@v7
        with:
          name: NUSspli-Aroma-DEBUG
          path: out/Aroma-DEBUG/*
          if-no-files-found: error
      - name: Upload Channel version
        uses: actions/upload-artifact@v7
        with:
          name: NUSspli-Channel-DEBUG
          path: out/Channel-DEBUG/*
          if-no-files-found: error
